ingress:
  host: buildmystudy.com
  pathType: Prefix

service:
  port: 80

spring:
  labels: spring
  image:
    repository: 440744253928.dkr.ecr.ap-northeast-2.amazonaws.com/chathub/backend   # ECR에 저장된 스프링 이미지 URL
    tag: latest
  service:
    port: 80
  containerPort: 8080
  datasource:
    url: jdbc:mysql://database-1.c9s06ug8a482.ap-northeast-2.rds.amazonaws.com:3306/mydb
    username: yourusername
    password: yourpassword
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "your-client-id"
            client-secret: "your-client-secret"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage : 75

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60